excluded: # paths to ignore during linting. Takes precedence over `included`.
- WeatherApp/AppDelegate.swift
- WeatherApp/SceneDelegate.swift
- WeatherAppTests/*
- Pods
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- line_length
